# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EcommDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EcommDemo
	pod 'AFNetworking', '~> 3.1'
	pod 'MBProgressHUD', '~> 1.0'		
  target 'EcommDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EcommDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
